---
- name: Create the network configuration file for bridge devices
  template:
    src: "bridge_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.device }}{{ network_interface_file_postfix }}"
  loop: "{{ network_bridge_interfaces }}"
  register: bridge_result
  notify: restart networking

- name: Create the network configuration file for port on the bridge devices
  template:
    src: "bridge_port_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.1 }}{{ network_interface_file_postfix }}"
  with_subelements:
    - '{{ network_bridge_interfaces }}'
    - bridge_ports
    - skip_missing: True
  register: bridge_port_result
  notify: restart networking

- name: Create the network configuration file for virtual port on the bridge devices
  template:
    src: "bridge_virtual_port_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.1 }}{{ network_interface_file_postfix }}"
  with_subelements:
    - '{{ network_bridge_interfaces }}'
    - bridge_ports_vlan_interface
    - skip_missing: True
  register: bridge_port_vlan_result
  notify: restart networking
